### ISSUE TITLE
Video quick start on docker usage?

### ISSUE THREAD

**Issue by lebeastmode** [torikushiii/hoyolab-auto#33]
Can you make a video quick start on docker usage?  I'm stuck on using the make file

**Comment by torikushiii** [comment]
you can ask where you are stuck. also, have you tried using docker-compose directly instead of using the Makefile to see if it helps?

**Comment by lebeastmode** [comment]
I don't know how to use docker in general :(

**Comment by torikushiii** [comment]
i'm assuming you're using windows. if so, you can follow this [guide](https://docs.docker.com/desktop/install/windows-install/#install-docker-desktop-on-windows) on how to install docker. after successfully installing it, you can proceed to follow the docker guide by running it directly instead of using a makefile.

If you still any further questions, feel free to ask.

**Comment by lebeastmode** [comment]
Yes that worked thanks!

**Comment by BoDDEneR** [comment]
I am very sorry to reopen this issue and asking such a newbie question, but I have install a Docker Desktop and have absolute zero understanding what is it. I was looking for a guide about an hour, and every guide starts with entering the command, but this window just don't have any command line.

Extremely sorry to asking this kind of question, but can anybody can guide me where to input commands?
![1](https://github.com/user-attachments/assets/b87fa163-f6cb-44eb-8c79-365addf226b7)

**Comment by torikushiii** [comment]
@BoDDEneR have you tried using command prompt? search for command prompt/terminal at your windows search bar and try typing `docker`, and you should see something like this

![image](https://github.com/user-attachments/assets/8d3edd1d-ac57-4767-89c9-94f21e0f7c85)
